# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

fibs = [1, 2]
sum = 2
limit = 4000000

while fibs.last < limit
  count = fibs.count
  num = fibs[count - 1] + fibs[count - 2]

  if num % 2 == 0 then
    puts num
    sum += num
  end

  fibs.push num
end

puts sum
