<?php
/**
 * Problem: Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2, the first
 * 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 *
 * Solution: Check each fib number to see if it's even.  If so, add to
 * the sum.  Do this in a loop while fib is less than 4,000,000
 *
 * Test: Fibs <= 40 are 1, 2, 3, 5, 8, 13, 21, 34
 * Evens are just 2, 8, 34
 * So the sum would be 2 + 8 + 34 = 44
 */

$total = 2;       // The first loop will miss this so I'll add it here
$max   = 4000000; // Highest allowed Fibonacci number to add

function fib($x, $y, $max, $total)
{
	$fib = $x + $y;
	if ($fib <= $max) {
		if ($fib % 2 == 0) {
			$total += $fib;
		}
		$fib = fib($y, $fib, $max, &$total);

		return $fib;
	} else {
		return 0;
	}
}


fib(1, 2, $max, &$total);

echo $total . "\n";
