<?php
/**
 * Problem: Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
 * Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
 * Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * Solution: Start with T286 and for each T, loop through H for a match.
 * If a match is found, loop through P for a match.  We check H first because
 * it's computationally more efficient.
 */

include "helper.php";

function t($n)
{
    return $n*($n+1)/2;
}

function p($n)
{
    return $n*(3*$n-1)/2;
}

function h($n)
{
    return $n*(2*$n-1);
}

$hFound = false;
$pFound = false;
$t = 286;
$p = 165;
$h = 143;
$pn = 0;
$hn = 0;

while (!($hFound && $pFound)) {
    $hFound = false;
    $pFound = false;
    $t++;
    $tn = t($t);
    // echo "t($t) = $tn\n";
    while ($hn < $tn) {
        $h++;
        $hn = h($h);
        // echo "h($h) = $hn\n";
        if ($hn == $tn) {
            $hFound = true;
        }
    }

    while ($pn < $tn) {
        $p++;
        $pn = p($p);
        // echo "p($p) = $pn\n";
        if ($pn == $tn) {
            $pFound = true;
        }
    }

    if (!($hFound && $pFound)) {
        $h--;
        $hn = h($h);
        $p--;
        $pn = p($p);
    }
}

result(1533776805, $tn);
